services:
    linklogger:
        container_name: linklogger
        image: ghcr.io/packetparker/linklogger:latest
        network_mode: host
        volumes:
            - /path/on/system:/data
        restart: on-failure