services:
    linklogger:
        container_name: linklogger
        image: ghcr.io/packetparker/linklogger:latest
        volumes:
            - /path/on/system:/data
        ports:
            - 6464:6464
        restart: unless-stopped