services:
    linklogger:
        container_name: linklogger
        image: ghcr.io/packetparker/linklogger:latest
        volumes:
            - /path/on/system:/data
        ports:
            - 5100:5000
        restart: always